const veggies = [
  "Avacado",
  "Asparagus",
  "Carrots",
  "Chickpeas",
  "Cucumber",
  "Egg Plants",
  "Garlic Clove",
  "Greem Tomatoes",
  "Green Beans",
  "Green Chilli",
  "Green Olives",
  "Jalapeno",
  "Leek",
  "Onions",
  "Peas",
  "Plum Tomatoes",
  "Red Onions",
  "Red Pepper",
  "Spinach",
  "Spring Onions",
  "Spuash",
  "Stir-fry Vegetables",
  "Tomatoes",
  "Vine Leaves",
  "Zucchini",
  "Sweetcorn",
  "Haricot Beans",
  "Yellow Pepper",
  "Green Pepper",
  "Tinned Tomatoes",
  "Wild Mushrooms",
  "Cabbage",
  "Vine Tomatoes",
  "Brussel Sprouts",
  "Creamed Corn",
  "Water Chestnut",
  "Bean Sprouts",
  "Scallions",
  "Wood Ear Mushrooms",
  "Yellow Onion",
  "Persian Cucumber",
  "Dill Pickles",
  "Iceburg Lettuce",
  "Mulukhiyah",
  "Celery",
  "Chopped Onion",
  "Chopped Tomatoes",
  "Lettuce",
  "Pitted Black Olives",
  "Turnips",
  "Frozen Peas",
];
const fruits = [
  "Lemon",
  "Lime",
  "Medjool Dates",
  "Orange",
  "Apricot",
  "Raspberries",
  "Blueberries",
  "Fruit Mix",
  "Dried Friut",
  "Cherry",
  "Glace Cherry",
  "Apples",
  "Pears",
  "Rhubarb",
];
